version: '3'

services:
  meulindoapp:
    restart: always
    build:
      context: .
      target: meulindoapp

    container_name: container_estudo_docker_sequelize
    volumes:
      - .:/home/app
    ports:
      - '3000:3000'
    environment:
      - TESTE=envteste

  meubdpostgres:
    image: postgres:latest
    container_name: postgres2_estudos_docker
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - database.env
    ports:
      - 5460:5432
volumes:
  database-data:

